build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
  # https://jupyterbook.org/en/stable/publish/readthedocs.html
  jobs:
    pre_build:
      - jupyter-book config sphinx .

conda:
  environment: environment.yml
